[2023-07-29T04:00:08.939+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bs_customer_invoice_dag.start_template_job scheduled__2023-07-28T04:00:00+00:00 [queued]>
[2023-07-29T04:00:08.945+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bs_customer_invoice_dag.start_template_job scheduled__2023-07-28T04:00:00+00:00 [queued]>
[2023-07-29T04:00:08.945+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-29T04:00:08.952+0000] {taskinstance.py:1327} INFO - Executing <Task(DataflowTemplatedJobStartOperator): start_template_job> on 2023-07-28 04:00:00+00:00
[2023-07-29T04:00:08.956+0000] {standard_task_runner.py:57} INFO - Started process 18865 to run task
[2023-07-29T04:00:08.959+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bs_customer_invoice_dag', 'start_template_job', 'scheduled__2023-07-28T04:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/bs_customer_invoice_chinook_dag.py', '--cfg-path', '/tmp/tmpi1v405es']
[2023-07-29T04:00:08.961+0000] {standard_task_runner.py:85} INFO - Job 62: Subtask start_template_job
[2023-07-29T04:00:08.995+0000] {task_command.py:410} INFO - Running <TaskInstance: bs_customer_invoice_dag.start_template_job scheduled__2023-07-28T04:00:00+00:00 [running]> on host 53e9620c1516
[2023-07-29T04:00:09.042+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='npdangkhoa2020@gmail.com' AIRFLOW_CTX_DAG_OWNER='okza' AIRFLOW_CTX_DAG_ID='bs_customer_invoice_dag' AIRFLOW_CTX_TASK_ID='start_template_job' AIRFLOW_CTX_EXECUTION_DATE='2023-07-28T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-28T04:00:00+00:00'
[2023-07-29T04:00:09.049+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-07-29T04:00:17.927+0000] {dataflow.py:425} INFO - Start waiting for done.
[2023-07-29T04:00:19.561+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_PENDING
[2023-07-29T04:00:19.563+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:00:30.954+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_RUNNING
[2023-07-29T04:00:30.958+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:00:42.426+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_RUNNING
[2023-07-29T04:00:42.430+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:00:52.819+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_RUNNING
[2023-07-29T04:00:52.822+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:01:03.415+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_RUNNING
[2023-07-29T04:01:03.421+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:01:14.906+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_RUNNING
[2023-07-29T04:01:14.910+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:01:25.337+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_RUNNING
[2023-07-29T04:01:25.341+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:01:35.742+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_RUNNING
[2023-07-29T04:01:35.745+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:01:46.124+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_RUNNING
[2023-07-29T04:01:46.129+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:01:56.541+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_RUNNING
[2023-07-29T04:01:56.546+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:02:07.014+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_RUNNING
[2023-07-29T04:02:07.033+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:02:17.391+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_RUNNING
[2023-07-29T04:02:17.400+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-29T04:02:27.774+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-1f957d59 is state: JOB_STATE_FAILED
[2023-07-29T04:02:27.782+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataflow.py", line 675, in execute
    append_job_name=self.append_job_name,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 116, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 116, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 702, in start_template_dataflow
    jobs_controller.wait_for_done()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 427, in wait_for_done
    while self._jobs and not all(self._check_dataflow_job_state(job) for job in self._jobs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 427, in <genexpr>
    while self._jobs and not all(self._check_dataflow_job_state(job) for job in self._jobs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 409, in _check_dataflow_job_state
    raise Exception(f"Google Cloud Dataflow job {job['name']} has failed.")
Exception: Google Cloud Dataflow job my-dataflow-job-1f957d59 has failed.
[2023-07-29T04:02:27.825+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=bs_customer_invoice_dag, task_id=start_template_job, execution_date=20230728T040000, start_date=20230729T040008, end_date=20230729T040227
[2023-07-29T04:02:27.848+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-07-29T04:02:27.849+0000] {configuration.py:676} WARNING - section/key [smtp/smtp_user] not found in config
[2023-07-29T04:02:27.849+0000] {email.py:268} INFO - Email alerting: attempt 1
[2023-07-29T04:02:27.856+0000] {configuration.py:676} WARNING - section/key [smtp/smtp_user] not found in config
[2023-07-29T04:02:27.857+0000] {email.py:268} INFO - Email alerting: attempt 1
[2023-07-29T04:02:27.858+0000] {taskinstance.py:1889} ERROR - Failed to send email to: npdangkhoa2020@gmail.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1558, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1628, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataflow.py", line 675, in execute
    append_job_name=self.append_job_name,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 116, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 116, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 702, in start_template_dataflow
    jobs_controller.wait_for_done()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 427, in wait_for_done
    while self._jobs and not all(self._check_dataflow_job_state(job) for job in self._jobs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 427, in <genexpr>
    while self._jobs and not all(self._check_dataflow_job_state(job) for job in self._jobs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 409, in _check_dataflow_job_state
    raise Exception(f"Google Cloud Dataflow job {job['name']} has failed.")
Exception: Google Cloud Dataflow job my-dataflow-job-1f957d59 has failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2295, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1887, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-07-29T04:02:27.918+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 62 for task start_template_job (Google Cloud Dataflow job my-dataflow-job-1f957d59 has failed.; 18865)
[2023-07-29T04:02:27.987+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-29T04:02:28.027+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
