[2023-07-26T08:18:29.403+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bs_customer_invoice_dag.start_template_job manual__2023-07-26T08:18:23.075973+00:00 [queued]>
[2023-07-26T08:18:29.408+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bs_customer_invoice_dag.start_template_job manual__2023-07-26T08:18:23.075973+00:00 [queued]>
[2023-07-26T08:18:29.408+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-26T08:18:29.415+0000] {taskinstance.py:1327} INFO - Executing <Task(DataflowTemplatedJobStartOperator): start_template_job> on 2023-07-26 08:18:23.075973+00:00
[2023-07-26T08:18:29.419+0000] {standard_task_runner.py:57} INFO - Started process 327 to run task
[2023-07-26T08:18:29.422+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bs_customer_invoice_dag', 'start_template_job', 'manual__2023-07-26T08:18:23.075973+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/bs_customer_invoice_chinook_dag.py', '--cfg-path', '/tmp/tmpfjy3xisa']
[2023-07-26T08:18:29.424+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask start_template_job
[2023-07-26T08:18:29.477+0000] {task_command.py:410} INFO - Running <TaskInstance: bs_customer_invoice_dag.start_template_job manual__2023-07-26T08:18:23.075973+00:00 [running]> on host 53e9620c1516
[2023-07-26T08:18:29.531+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='datokza@gmail.com' AIRFLOW_CTX_DAG_OWNER='okza' AIRFLOW_CTX_DAG_ID='bs_customer_invoice_dag' AIRFLOW_CTX_TASK_ID='start_template_job' AIRFLOW_CTX_EXECUTION_DATE='2023-07-26T08:18:23.075973+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-26T08:18:23.075973+00:00'
[2023-07-26T08:18:29.538+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-07-26T08:18:35.184+0000] {dataflow.py:425} INFO - Start waiting for done.
[2023-07-26T08:18:36.455+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_PENDING
[2023-07-26T08:18:36.459+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:18:46.755+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:18:46.758+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:18:57.885+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:18:57.893+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:19:08.210+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:19:08.215+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:19:18.604+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:19:18.606+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:19:28.886+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:19:28.889+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:19:39.210+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:19:39.217+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:19:49.490+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:19:49.493+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:19:59.808+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:19:59.813+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:20:10.078+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:20:10.084+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:20:20.393+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:20:20.401+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:20:30.659+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:20:30.662+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:20:40.947+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:20:40.954+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:20:51.224+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:20:51.225+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:21:01.509+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:21:01.512+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:21:11.805+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:21:11.808+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:21:22.190+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:21:22.199+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:21:32.447+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:21:32.448+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:21:42.821+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:21:42.824+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:21:53.132+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:21:53.138+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:22:03.391+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:22:03.393+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:22:13.753+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:22:13.760+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:22:24.043+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:22:24.047+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:22:34.311+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:22:34.312+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:22:44.680+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:22:44.688+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:22:54.965+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:22:54.967+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:23:05.254+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_RUNNING
[2023-07-26T08:23:05.256+0000] {dataflow.py:428} INFO - Waiting for done. Sleep 10 s
[2023-07-26T08:23:15.543+0000] {dataflow.py:388} INFO - Google Cloud DataFlow job my-dataflow-job-a918e8b4 is state: JOB_STATE_FAILED
[2023-07-26T08:23:15.557+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataflow.py", line 675, in execute
    append_job_name=self.append_job_name,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 116, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 116, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 702, in start_template_dataflow
    jobs_controller.wait_for_done()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 427, in wait_for_done
    while self._jobs and not all(self._check_dataflow_job_state(job) for job in self._jobs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 427, in <genexpr>
    while self._jobs and not all(self._check_dataflow_job_state(job) for job in self._jobs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 409, in _check_dataflow_job_state
    raise Exception(f"Google Cloud Dataflow job {job['name']} has failed.")
Exception: Google Cloud Dataflow job my-dataflow-job-a918e8b4 has failed.
[2023-07-26T08:23:15.579+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=bs_customer_invoice_dag, task_id=start_template_job, execution_date=20230726T081823, start_date=20230726T081829, end_date=20230726T082315
[2023-07-26T08:23:15.602+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-07-26T08:23:15.603+0000] {configuration.py:676} WARNING - section/key [smtp/smtp_user] not found in config
[2023-07-26T08:23:15.604+0000] {email.py:268} INFO - Email alerting: attempt 1
[2023-07-26T08:23:15.611+0000] {configuration.py:676} WARNING - section/key [smtp/smtp_user] not found in config
[2023-07-26T08:23:15.612+0000] {email.py:268} INFO - Email alerting: attempt 1
[2023-07-26T08:23:15.613+0000] {taskinstance.py:1889} ERROR - Failed to send email to: datokza@gmail.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1558, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1628, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataflow.py", line 675, in execute
    append_job_name=self.append_job_name,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 116, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 116, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 702, in start_template_dataflow
    jobs_controller.wait_for_done()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 427, in wait_for_done
    while self._jobs and not all(self._check_dataflow_job_state(job) for job in self._jobs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 427, in <genexpr>
    while self._jobs and not all(self._check_dataflow_job_state(job) for job in self._jobs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 409, in _check_dataflow_job_state
    raise Exception(f"Google Cloud Dataflow job {job['name']} has failed.")
Exception: Google Cloud Dataflow job my-dataflow-job-a918e8b4 has failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2295, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1887, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-07-26T08:23:15.634+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 36 for task start_template_job (Google Cloud Dataflow job my-dataflow-job-a918e8b4 has failed.; 327)
[2023-07-26T08:23:15.678+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-26T08:23:15.741+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
